version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint"
          - "@eslint-community"
          - "eslint-*"
          - "@stylistic"
          - "@typescript-eslint/*"
          - "typescript-eslint"
      types:
        patterns:
          - "@types/*"
      obsidian:
        patterns:
          - "obsidian"
          - "obsidian-typings"
      typescript:
        patterns:
          - "typescript"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      testing-library:
        patterns:
          - "@testing-library/*"
      build-tools:
        patterns:
          - "esbuild"
          - "rollup"
          - "vite"
      lint-staged:
        patterns:
          - "lint-staged"
      prettier:
        patterns:
          - "prettier"
      semantic-release:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
