blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/snelling-a/obsidian-song-of-the-day/blob/main/README.md
    about: Read the documentation and setup guide
  - name: Contributing Guide
    url: https://github.com/snelling-a/obsidian-song-of-the-day/blob/main/docs/CONTRIBUTING.md
    about: Learn how to contribute to the project
  - name: Roadmap
    url: https://github.com/snelling-a/obsidian-song-of-the-day/blob/main/docs/ROADMAP.md
    about: Check planned features before requesting
